const adminAT = {
  GET_ALL_USERS_REQUEST: "ADMIN_GET_ALL_USERS_REQUEST",
  GET_ALL_USERS_SUCCESS: "ADMIN_GET_ALL_USERS_SUCCESS",
  GET_ALL_USERS_FAILURE: "ADMIN_GET_ALL_USERS_FAILURE",
  GET_USER_PROFILES_REQUEST: "ADMIN_GET_USER_PROFILES_REQUEST",
  GET_USER_PROFILES_SUCCESS: "ADMIN_GET_USER_PROFILES_SUCCESS",
  GET_USER_PROFILES_FAILURE: "ADMIN_GET_USER_PROFILES_FAILURE",
  GET_DASHBOARD_REQUEST: "ADMIN_GET_DASHBOARD_REQUEST",
  GET_DASHBOARD_SUCCESS: "ADMIN_GET_DASHBOARD_SUCCESS",
  GET_DASHBOARD_FAILURE: "ADMIN_GET_DASHBOARD_FAILURE",
  UPDATE_USER_PROFILE: "ADMIN_UPDATE_USER_PROFILE",
  UPDATE_USER: "ADMIN_UPDATE_USER",
  DELETE_USER: "ADMIN_DELETE_USER",
  DELETE_USER_PROFILE: "ADMIN_DELETE_USER_PROFILE",
  CREATE_USER_PROFILE: "ADMIN_CREATE_USER_PROFILE",
};

export default adminAT;
