const usersAT = {
  LOGIN_REQUEST: "USERS_LOGIN_REQUEST",
  LOGIN_SUCCESS: "USERS_LOGIN_SUCCESS",
  LOGIN_FAILURE: "USERS_LOGIN_FAILURE",
  REGISTER_REQUEST: "USERS_REGISTER_REQUEST",
  REGISTER_SUCCESS: "USERS_REGISTER_SUCCESS",
  REGISTER_FAILURE: "USERS_REGISTER_FAILURE",
  LOGOUT: "USERS_LOGOUT",
  GET_ALL_USERS_REQUEST: "USERS_GET_ALL_USERS_REQUEST",
  GET_ALL_USERS_SUCCESS: "USERS_GET_ALL_USERS_SUCCESS",
  GET_ALL_USERS_FAILURE: "USERS_GET_ALL_USERS_FAILURE",
  GET_ALL_PROFILES_REQUEST: "USERS_GET_ALL_PROFILES_REQUEST",
  GET_ALL_PROFILES_SUCCESS: "USERS_GET_ALL_PROFILES_SUCCESS",
  GET_ALL_PROFILES_FAILURE: "USERS_GET_ALL_PROFILES_FAILURE",
};

export default usersAT;
